version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"   # پورت 5001 روی سیستم شما، 5000 داخل کانتینر
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8089:80"     # پورت 8081 روی سیستم شما، 80 داخل کانتینر
    restart: unless-stopped